version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: medical_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=medical_tele_expertise
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
